name: pubghost
description: A CLI tool to find unused translations, dependencies or classes in a Flutter project.
version: 1.0.7
repository: https://github.com/YarnoVdW/pubghost
homepage: https://github.com/YarnoVdW/pubghost

environment:
  sdk: ">3.0.0 <4.0.0"

dependencies:
  path: ^1.9.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.6

executables:
  pubghost: pubghost
