name: pubghost
description: A CLI tool to find unused translations, dependencies or classes in a Flutter project.
version: 1.0.2
repository: https://github.com/YarnoVdW/pubghost
homepage: https://github.com/YarnoVdW/pubghost

environment:
  sdk: ^3.9.2

dependencies:
  path: ^1.9.0
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  pubghost: pubghost
